steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials mobilex-$_ENV_NAME-cluster --region=us-central1 
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=mobilex-$_ENV_NAME-cluster'   
      
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'job.yaml', '--namespace=mobilexan']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=mobilex-$_ENV_NAME-cluster'
    
substitutions:
  _ENV_NAME: 'default_value'
